apiVersion: apps/v1
kind: Deployment
metadata:
  name: cats
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: cats
  template:
    metadata:
      labels:
        app: cats
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: cat-container
        image: 866477832211.dkr.ecr.ap-northeast-2.amazonaws.com/abc-cats:20241107.072310
        resources:
          requests:
            cpu: 250m
---
apiVersion: v1
kind: Service
metadata:
  name: cats-svc
  labels:
    app: cats
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: cats