apiVersion: apps/v1
kind: Deployment
metadata:
  name: cats
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: cats
  template:
    metadata:
      labels:
        app: cats
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: cat-container
        image: image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        resources:
          requests:
            cpu: 250m
---
apiVersion: v1
kind: Service
metadata:
  name: cats-svc
  labels:
    app: cats
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: cats
