apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: web-container
        image: 866477832211.dkr.ecr.ap-northeast-2.amazonaws.com/abc-cats:20241107.072310
        resources:
          requests:
            cpu: 250m
