apiVersion: apps/v1
kind: Deployment
metadata:
  name: dogs
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: dogs
  template:
    metadata:
      labels:
        app: dogs
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: dog-container
        image: {{ .Values.image.websrepository }}:{{ .Values.image.tag }}
        resources:
          requests:
            cpu: 250m
---
apiVersion: v1
kind: Service
metadata:
  name: dogs-svc
  labels:
    app: dogs
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: dogs
