apiVersion: apps/v1
kind: Deployment
metadata:
  name: webs
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: webs
  template:
    metadata:
      labels:
        app: webs
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: web-container
        image: 866477832211.dkr.ecr.ap-northeast-2.amazonaws.com/abc-webs:20241107.072310
        resources:
          requests:
            cpu: 250m
---
apiVersion: v1
kind: Service
metadata:
  name: webs-svc
  labels:
    app: webs
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: webs
